source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Twitter App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSPlayground

  pod 'Alamofire', '~> 4.3'  
  pod 'SwiftyJSON'
  pod 'Kingfisher', '~> 3.0'

end
